name: example
description: A new Flutter project.

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"

dependencies:

  flutter:
    sdk: flutter

  pull_to_refresh:
    path: ../


  http: 0.12.0

  flutter_staggered_grid_view: ^0.3.0

  flutter_spinkit: 2.1.0

  residemenu: 1.3.7

  fish_redux: ^0.2.2

  shimmer: 1.0.0

  flutter_sticky_header: ^0.4.0

  flutter_gifimage: ^1.0.0

  flutter_swiper : ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_localizations:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  assets:
    - images/animate.gif
    - images/empty.png
    - images/empty1.png
    - images/secondfloor.jpg
    - images/classical_follow.gif
    - images/classical_unfollow.gif
    - images/bezier.gif
    - images/warterdrop.gif
    - images/material_classic.gif
    - images/material_waterdrop.gif
    - images/qqbg.jpg
    - images/custom_1.jpg
    - images/gifindicator1.gif
    - images/msg_text_right_bg.9.png
    - images/custom_2.gif
    - images/loadstyle1.gif
    - images/loadstyle2.gif
    - images/loadstyle3.gif
    - images/refreshstyle1.gif
    - images/refreshstyle2.gif
    - images/refreshstyle3.gif
    - images/refreshstyle4.gif
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
