name: pull_to_refresh
description: a widget provided to the flutter scroll component drop-down refresh and pull up load.
version: 1.5.2
author: Jpeng <peng8350@gmail.com>
homepage: https://github.com/peng8350/flutter_pulltorefresh

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
